### ISSUE TITLE
F1nn threads.

### ISSUE THREAD

**Issue by Zcully** [bigkrimpin/f1nn5ter_threads#2]
https://boards.4channel.org/lgbt/thread/23960705#p23985068
https://boards.4channel.org/lgbt/thread/23990953#p23990953
https://boards.4channel.org/lgbt/thread/24014609#p24030169
https://boards.4channel.org/lgbt/thread/24035163#p24036160
https://boards.4channel.org/lgbt/thread/24050789#p24062021
https://boards.4channel.org/lgbt/thread/24063404#p24075231

**Comment by bigkrimpin** [comment]
Added them
